Tupla_Dias_Del_Mes=(31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)
print(Tuplas_Dia_Del_Mes)
print(Tuplas_Dia_Del_Mes[0])
print(Tuplas_Dia_Del_Mes[3])
print(Tuplas_Dia_Del_Mes[1])
Tupla_Numeros=(('cero', 0), ('uno', 1, 'UNO'), ('dos', 2), ('tres', 3), ('cuatro', 4), ('x', 5))
print(Tupla_Numeros)
print(Tupla_Numeros[0])
print(Tupla_Numeros[1])
print(Tupla_Numeros[2][0])
print(Tupla_Numeros[2][1])
print(Tupla_Numeros[1][0])
print(Tupla_Numeros[1][1])
print(Tupla_Numeros[1][2])
print("VALOR ACTUAL {}".format(Tupla_Numeros[0]))
Lista_Dias_Del_Mes[0] = 50
print("VALOR CAMBIADO {}".format(Tupla_Numeros[0]))
Tupla_Dias_Del_Mes[0] = 50
from collections import namedtuple
planeta = namedtuple('Planeta', ['Nombre', 'Numero'])
Planeta1 = Planeta(Mercurio, 1)
print(Planeta1)
Planeta2 = Planeta(Venus, 2)
print(Planeta1.Nombre, Planeta1.Numero)
print(Planeta2[0], Planeta2[1])
print("CAMBIOS EN LA TUPLA {}".format(Planeta1._fields))
